name: tic_tac_toe_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
